[package]
authors = ["Timo Renk <renk.git@gmail.com>"]
edition = "2021"
name = "kernel"
readme = "README.md"
version = "0.1.0"

[dependencies]
riscv_utils = { path = "../riscv" }
enum_matching = { path = "../enum_matching" }
