[package]
authors = ["Timo Renk <renk.git@gmail.com>"]
edition = "2021"
name = "user_progs"
readme = "README.md"
version = "0.1.0"

[dependencies]
riscv_utils = { path = "../riscv" }

[[bin]]
name = "user_1"
path = "src/user_1.rs"

[[bin]]
name = "user_2"
path = "src/user_2.rs"
